# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Build Liara
      working-directory: ./modules/liara
      run: go build -v ./...

    - name: Build LiaraCtl
      working-directory: ./modules/liaractl
      run: go build -v ./...

    - name: Build LiaraService
      working-directory: ./services/liara_service
      run: go build -v ./...

    - name: Build LiaraDB
      working-directory: ./services/liaradb
      run: go build -v ./...

    - name: Test Liara
      working-directory: ./modules/liara
      run: go test -v ./...

    - name: Test LiaraCtl
      working-directory: ./modules/liaractl
      run: go test -v ./...

    - name: Test LiaraService
      working-directory: ./services/liara_service
      run: go test -v ./...

    - name: Test
      working-directory: ./services/liaradb
      run: go test -v ./...
