# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Liara

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/liarasql.yml
      - modules/eventsource_go/**
      - services/liarasql/**
  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/liarasql.yml
      - modules/eventsource_go/**
      - services/liarasql/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: services/liarasql/go.mod
          cache-dependency-path: |
            modules/eventsource_go/go.sum
            services/liarasql/go.sum

      - name: Build LiaraService
        working-directory: ./services/liarasql
        run: go build -v ./...

      - name: Test LiaraService
        working-directory: ./services/liarasql
        run: go test -v ./...
