# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: LiaraDB

on:
  push:
    branches:
      - "main"
    paths:
      - .github/workflows/liaradb.yml
      - services/liaradb/**
  pull_request:
    branches:
      - "main"
    paths:
      - .github/workflows/liaradb.yml
      - services/liaradb/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: services/liaradb/go.mod
          cache-dependency-path: services/liaradb/go.sum

      - name: Build
        working-directory: ./services/liaradb
        run: make build

      - name: Test
        working-directory: ./services/liaradb
        run: make report-file

      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ./services/liaradb/cover.html
          retention-days: 5

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: liaradb
          path: ./services/liaradb/bin/liaradb
          retention-days: 5
